version: "3.7"

services:
  my-backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/backend/src:/myfolder/src
    env_file:
      - ./services/backend/.env
    ports:
      - 3000:3000

  socket:
    build:
      context: ./services/socket
      dockerfile: Dockerfile
    volumes:
      - ./services/socket/src:/socket/src
    ports:
      - 3002:3002
      
  api-gateway:
    image: nginx:latest
    volumes:
      - ./api-gateway/default.conf:/etc/nginx/conf.d/default.conf
      - ./api-gateway/frontend/html:/etc/nginx/html
    ports:
      - 80:80

  my-database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'mydocker03'
      MYSQL_ROOT_PASSWORD: 'ASDasd123!'
    ports:
      - 3306:3306

  redis:
    image: redis:latest
    ports:
      - 6379:6379
